
general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = home/Documents/wallpapers/tokyonight/tn-cyberpunkwall2.png 
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.5
    dots_center = true
    outer_color = rgb(40,40,40)
    inner_color = rgb(10,10,10)
    font_color = rgb(200,200,200)
    fade_on_empty = false
    placeholder_text = ""
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}
